### ISSUE TITLE
Questions about the Relavance Matrix

### ISSUE THREAD

**Issue by Paandaman** [hila-chefer/Transformer-MM-Explainability#12]
First of all, thanks for the great work! It's always nice with approaches that are not too complicated to implement but still yield impressive results!

I have a question regarding the final Relevancy matrix. In the code for the different models I see that before the relevancy matrix is sent back, we pick out the scores for the first token and then remove the "self" relevancy score for this token R[0, 1:]. This is done since in this case this token represents the CLS token, right? And the "self" relevancy is removed since we only want to keep the entries for the tokens from the original data, is that correct?  
![image](https://user-images.githubusercontent.com/16947381/147631384-6d77e87b-9b3a-41b2-9297-dca63b322177.png)
I am using your approach for a GPT model and it has been working well. I initially tested it on a toy problem where the model had to predict whether a certain word was present in the input or not (classification was done on a SEP token at the end of the sequence) and the relevancy score properly highlighted the words if they were present. I am now  trying to generate embeddings for another task by extracting the final SEP token and using it as embedding. I have tried a similar approach to the positive and negative perturbation from your paper and noticed that I can remove up to 90% of the tokens from the input and still get very similar final embeddings. My issue is now how to interpret these tokens that get high relevance scores. For some reason the token at position 0 almost always get the highest score and in this case this token is not the CLS token, instead it can be any token from the vocabulary. So this made me question if there perhaps were any other reasons why R[0, 1:] is performed in your code?

**Comment by hila-chefer** [comment]
Hi @Paandaman, thanks for your interest in our work!
You are absolutely correct, the removal of relevance score of the first token is since the first token is the CLS which is a dummy token and does not represent real data.
In general, we mention in the paper that since the relevance matrix is initialized with the identity for self attention, the scores of the diagonal tend to have a larger value than the other relevance scores, but in this case it has no effect since we remove `R[0,0]`.
I’m glad to hear our approach proved to be beneficial for GPT! If you’re willing to, I’d be happy to add your code to our repo so other people can use it and get inspired by your work :) (you can open a pull request and I’ll merge your code to our repo).

Regarding your issue, it is interesting, I haven’t seen this phenomenon in any other case.
I have seen that when you use special tokens such as `CLS, SEP` they sometimes have a higher relevance score than other tokens (perhaps because they appear in every input), but this phenomenon is not one I’m familiar with.
I would suggest to try to limit the context expansion and see what happens [as I suggested in this issue regarding CLIP](https://github.com/hila-chefer/Transformer-MM-Explainability/issues/8) and you can also refer to our colab to see an example of context expansion for CLIP.

I hope this helps, and I hope you’ll share your code for GPT as well :)

Best,
Hila.

**Comment by Paandaman** [comment]
Thank you for the informative reply! 
That makes a lot of sense, thanks for clarifying it! I would love to share the GPT code but it's currently written together with some  proprietary code so I will have to create a stand-alone version of it first. I will try to do it!

Interesting indeed! I am using a lot of SEP tokens to separate different parts of the text and I have also noticed that these SEP tokens often get high scores. I was thinking that maybe the model is aggregating the information from the sequence of tokens into these SEP tokens in the same way as BERT uses the CLS token, but since there are several SEP tokens maybe it can store different parts of the information in different SEP tokens. If this is the case it might make sense that they get a high score! 
Thanks for the suggestion, I tried limiting the context expansion but did not actually see any difference, the first token still gets the highest scores! I will have to try and dig deeper into this to see if it makes sense or not! 

Many thanks once again! 

Best regards,
Max
