### ISSUE TITLE
Question about the CLIP Demo

### ISSUE THREAD

**Issue by Hoyyyaard** [hila-chefer/Transformer-MM-Explainability#24]
Hello, I have two questions about the CLIP demo, may I take the liberty of asking you?
(1) variable "image_relevance" in function "interpret"
This code "image_relevance = R[:, 0, 1:]"applied after updating the attention prob map; I confused about why choosing the first row of the relevant scores ; Is this corresponding to the saying in paper " to ex-tract relevancies per text token, one should consider the first row of Rtt, and to extract the image token relevancies, consider the first row in Rti which describes the connections between the [CLS] token and each image token"  in section 3.1? Or can you give me some other insights? 

(2) variable "R_text" in function "show_heatmap_on_text"
I also confused about why "CLS_idx = text_encoding.argmax(dim=-1)", The [CLS] token is usually the first one in tokens. Can you give me some insights about this ?

Thanks!

**Comment by hila-chefer** [comment]
Hi @Hoyyyaard, thanks for your interest!
1. Indeed, this code extracts the relevance scores for the CLS token, which is the first token for the image sequence. We also discard the first token’s relevance since the first token is the CLS itself.
2. Usually the CLS token is the first one (especially for image sequences). In the case of the text sequence, this is the code to extract the CLS index by the official implementation, so again, this code simply extracts the CLS location to use it for the interpretation.

I hope this helps.
Best,
Hila.
